require 'dry/logic/operations/conjunction'
require 'dry/logic/operations/disjunction'
require 'dry/logic/operations/exclusive_disjunction'
require 'dry/logic/operations/implication'
require 'dry/logic/operations/negation'

require 'dry/logic/operations/key'
require 'dry/logic/operations/attr'
require 'dry/logic/operations/each'
require 'dry/logic/operations/set'
require 'dry/logic/operations/check'
